development:
   adapter: mysql
   database: kaizen
   username: kaizenuser
   password: l8nd5c8p37
   host: kaizen-staging.csltrie4omxw.us-west-2.rds.amazonaws.com	
test:
   adapter: mysql
   database: kaizen
   username: kaizenuser
   password: l8nd5c8p37
   host: kaizen-staging.csltrie4omxw.us-west-2.rds.amazonaws.com
production:
   adapter: mysql
   database: kaizen
   username: kaizenuser
   password: l8nd5c8p37
   host: kaizen-staging.csltrie4omxw.us-west-2.rds.amazonaws.com
